apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: qkrafr2py-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/qkrafr2py-java-quarkus-gitops